### ISSUE TITLE
Unable to access server.jar

### ISSUE THREAD

**Issue by alarmingteaspoon** [BrandonDusseau/minecraft-scripts#1]
Here's the error message that appears in the screen:

> cd /opt/minecraft/server
/usr/bin/bash -c "exec -a minecraft /usr/bin/java -Xmx1024M -Xm2048M -d64 -jar opt/minecraft/server/server.jar nogui"
root@server:/opt/minecraft# cd /opt/minecraft/server
root@server:/opt/minecraft/server# /usr/bin/bash -c "exec -a minecraft /usr/bin/java -Xmx1024M -Xm2048M -d64 -jar opt/minecraft/server/server.jar nogui"
Error: Unable to access jarfile opt/minecraft/server/server.jar
root@server:/opt/minecraft/server#

I'm new to Linux, so I apologise if this isn't enough to help, just ask for any other errors if you need to

**Comment by BrandonDusseau** [comment]
Hey! It looks like you might have missed the leading / on your server jar location. Make sure it begins with `/opt` instead of `opt`.

**Comment by BrandonDusseau** [comment]
I assume this has been solved for you as I haven't heard anything within a month. Closing this.
